### ISSUE TITLE
Repeated Keyword Argument In Sites Extension

### ISSUE THREAD

**Issue by jobala** [Azure/autorest.az#821]
**Command**
mg sites site list --site-id ENTER_ID

**Stacktrace**
```python
The command failed with an unexpected error. Here is the traceback:
'SitesSiteOperations' object has no attribute 'list_sites'
Traceback (most recent call last):
  File "/Users/jobala/.local/share/virtualenvs/msgraph-cli-experiment-PdxeK3ZY/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/jobala/.local/share/virtualenvs/msgraph-cli-experiment-PdxeK3ZY/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 660, in execute
    raise ex
  File "/Users/jobala/.local/share/virtualenvs/msgraph-cli-experiment-PdxeK3ZY/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 728, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/Users/jobala/.local/share/virtualenvs/msgraph-cli-experiment-PdxeK3ZY/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_job
    six.reraise(*sys.exc_info())
  File "/Users/jobala/.local/share/virtualenvs/msgraph-cli-experiment-PdxeK3ZY/lib/python3.9/site-packages/six.py", line 703, in reraise
    raise value
  File "/Users/jobala/.local/share/virtualenvs/msgraph-cli-experiment-PdxeK3ZY/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 694, in _run_job
    result = cmd_copy(params)
  File "/Users/jobala/.local/share/virtualenvs/msgraph-cli-experiment-PdxeK3ZY/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/jobala/.local/share/virtualenvs/msgraph-cli-experiment-PdxeK3ZY/lib/python3.9/site-packages/azure/cli/core/__init__.py", line 811, in default_command_handler
    return op(**command_args)
  File "/Users/jobala/.local/share/virtualenvs/msgraph-cli-experiment-PdxeK3ZY/lib/python3.9/site-packages/azext_sites/generated/custom.py", line 275, in sites_site_list
    return client.list_sites(site_id=site_id,
AttributeError: 'SitesSiteOperations' object has no attribute 'list_sites'
```

**Comment by changlong-liu** [comment]
need to change operationid in openapi.

follow up in az: shall check clientfactory when grouping operations
